In [2]:
import numpy as np
from sklearn.decomposition import NMF

In [49]:
X = np.array([[10, 12, 120], [20, 12, 120], [30, 13, 130], [40, 13, 120], [50, 12, 120], [50, 12, 120]])
print(f"X has shape {X.shape}")
print(X)

X has shape (6, 3)
[[ 10  12 120]
 [ 20  12 120]
 [ 30  13 130]
 [ 40  13 120]
 [ 50  12 120]
 [ 50  12 120]]


In [33]:
#model = NMF(n_components=2, init="nndsvd", random_state=0)
model = NMF(n_components=2, init="nndsvd")

In [34]:
W = model.fit_transform(X)
H = model.components_

In [35]:
print(f"W has shape {W.shape}")
print(W)

[[6.89158616 0.        ]
 [6.89130585 0.79231435]
 [7.46533013 1.51884968]
 [6.89638385 2.37729765]
 [6.89040148 3.17014724]
 [6.89040148 3.17014724]]


In [36]:
print(f"H has shape {H.shape}")
print(H)

[[ 1.45146456  1.74721698 17.41190254]
 [12.61696655  0.06671962  0.        ]]


In [46]:
X2 = np.matmul(W,H)
X2 = np.around(X2, decimals=0)

In [50]:
print(f"The product of W and H has shape {X2.shape}")
print(X2)

The product of W and H has shape (6, 3)
[[ 10.  12. 120.]
 [ 20.  12. 120.]
 [ 30.  13. 130.]
 [ 40.  12. 120.]
 [ 50.  12. 120.]
 [ 50.  12. 120.]]
